name: "Issue Actions"
on:
  issues:
    types: [labeled, edited]

jobs:
  Bender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: openquiz/actions@v1.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          patch-branch: "bot-patch"
          administrators: "[leplay]"
          editors-friends: "[nicing]"